# Generated by Django 2.1.5 on 2019-01-15 19:08

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='PostContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(editable=False, verbose_name='Text')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name=django.contrib.auth.models.User)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_contents', to='blog.Post', verbose_name='Post')),
            ],
        ),
    ]
